services:
  # 1. Database: PostGIS
  db:
    image: postgis/postgis:15-3.3
    container_name: spotential_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: spotential
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # 2. Backend: FastAPI
  backend:
    build: ./backend
    container_name: spotential_backend
    # syncs local code so to reloads on save
    volumes:
      - ./backend:/app
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/spotential
    ports:
    # map the computer port to container port
      - "8000:8000"
    depends_on:
      - db


volumes:
  postgres_data: