/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/business/menu": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Menu */
        get: operations["get_menu_business_menu_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/business/tract/{tract_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Business From Tract */
        get: operations["get_business_from_tract_business_tract__tract_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/locations/analysis": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Analysis */
        get: operations["get_analysis_locations_analysis_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/census/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Find Tract */
        get: operations["find_tract_census_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/census/{tract_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Tract Details */
        get: operations["get_tract_details_census__tract_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/agent/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Chat */
        post: operations["chat_agent_chat_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AgentChatRequest */
        AgentChatRequest: {
            /** Messages */
            messages: components["schemas"]["AgentMessage"][];
        };
        /** AgentChatResponse */
        AgentChatResponse: {
            /** Reply */
            reply: string;
            /** Results */
            results: components["schemas"]["AgentLocationResult"][];
        };
        /** AgentLocationResult */
        AgentLocationResult: {
            /** Tract Id */
            tract_id: string;
            /** Label */
            label: string;
            business_type: components["schemas"]["BusinessType"];
            /** Score */
            score: number;
            /** Lat */
            lat: number;
            /** Lng */
            lng: number;
            /** Predicted Count */
            predicted_count: number;
            /** Actual Count */
            actual_count: number;
            /** Neighbourhood */
            neighbourhood?: string | null;
            /** City */
            city?: string | null;
            /** State */
            state?: string | null;
            /** Country */
            country?: string | null;
        };
        /** AgentMessage */
        AgentMessage: {
            /**
             * Role
             * @enum {string}
             */
            role: "user" | "assistant";
            /** Content */
            content: string;
        };
        /** AnalysisResponse */
        AnalysisResponse: {
            tract: components["schemas"]["TractFeature"];
            businesses: components["schemas"]["BusinessCollection"];
            tract_stats: components["schemas"]["TractStats"];
            demographics: components["schemas"]["CensusDemographicsBase"];
        };
        /** BusinessBase */
        BusinessBase: {
            /** Osm Id */
            osm_id: number;
            /** Tract Id */
            tract_id?: string | null;
            /** Name */
            name: string;
            type: components["schemas"]["BusinessType"];
            category: components["schemas"]["BusinessCategory"];
            /** Website */
            website?: string | null;
            /** Opening Hours */
            opening_hours?: string | null;
            /** Lng */
            lng: number;
            /** Lat */
            lat: number;
        };
        /**
         * BusinessCategory
         * @enum {string}
         */
        BusinessCategory: "fitness" | "food & drink" | "retail" | "service";
        /** BusinessCategoryResponse */
        BusinessCategoryResponse: {
            /** Key */
            key: string;
            /** Label */
            label: string;
            /** Business */
            business: components["schemas"]["BusinessTypeResponse"][];
        };
        /** BusinessCollection */
        BusinessCollection: {
            /**
             * Type
             * @default FeatureCollection
             * @constant
             */
            type: "FeatureCollection";
            /** Features */
            features: components["schemas"]["BusinessFeature"][];
        };
        /** BusinessFeature */
        BusinessFeature: {
            /**
             * Type
             * @default Feature
             * @constant
             */
            type: "Feature";
            geometry: components["schemas"]["Geometry"];
            properties: components["schemas"]["BusinessBase"];
        };
        /**
         * BusinessType
         * @enum {string}
         */
        BusinessType: "fitness_centre" | "restaurant" | "cafe" | "fast_food" | "bar" | "supermarket" | "convenience" | "bakery" | "bank" | "clinic" | "dentist";
        /** BusinessTypeResponse */
        BusinessTypeResponse: {
            /** Key */
            key: string;
            /** Label */
            label: string;
        };
        /** BusinessWithGeometry */
        BusinessWithGeometry: {
            business: components["schemas"]["BusinessBase"];
            /** Geometry */
            geometry: {
                [key: string]: unknown;
            };
        };
        /** CensusDemographicsBase */
        CensusDemographicsBase: {
            /** Tract Id */
            tract_id: string;
            /** Population */
            population?: number | null;
            /** Population Density */
            population_density?: number | null;
            /** Count Age 15 64 */
            count_age_15_64?: number | null;
            /** Household Count */
            household_count?: number | null;
            /** Median Household Income */
            median_household_income?: number | null;
            /** Education Base Pop 25 Plus */
            education_base_pop_25_plus?: number | null;
            /** Count Postsecondary Edu Plus */
            count_postsecondary_edu_plus?: number | null;
            /** Pct Working Age */
            pct_working_age?: number | null;
            /** Pct Highly Educated */
            pct_highly_educated?: number | null;
            /** Avg Household Size */
            avg_household_size?: number | null;
        };
        /** CensusInfoResponse */
        CensusInfoResponse: {
            /** Tract Id */
            tract_id: string;
            demographics: components["schemas"]["CensusDemographicsBase"];
            /** Geometry */
            geometry: {
                [key: string]: unknown;
            };
        };
        /** Geometry */
        Geometry: {
            /**
             * Type
             * @enum {string}
             */
            type: "Point" | "LineString" | "Polygon" | "MultiPolygon";
            /** Coordinates */
            coordinates: unknown;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** TractFeature */
        TractFeature: {
            /**
             * Type
             * @default Feature
             * @constant
             */
            type: "Feature";
            geometry: components["schemas"]["Geometry"];
            properties: components["schemas"]["TractFeatureProps"];
        };
        /** TractFeatureProps */
        TractFeatureProps: {
            /** Tract Id */
            tract_id: string;
            /** Score */
            score: number;
        };
        /** TractStats */
        TractStats: {
            /** Tract Id */
            tract_id: string;
            /** Score */
            score: number;
            /** Business In Tract */
            business_in_tract: number;
            /** Predicted Count */
            predicted_count: number;
            /** Actual Count */
            actual_count: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_menu_business_menu_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BusinessCategoryResponse"][];
                };
            };
        };
    };
    get_business_from_tract_business_tract__tract_id__get: {
        parameters: {
            query?: {
                business_type?: components["schemas"]["BusinessType"] | null;
            };
            header?: never;
            path: {
                tract_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BusinessWithGeometry"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_analysis_locations_analysis_get: {
        parameters: {
            query: {
                lng: number;
                lat: number;
                business_type: components["schemas"]["BusinessType"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysisResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    find_tract_census_search_get: {
        parameters: {
            query: {
                lng: number;
                lat: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_tract_details_census__tract_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tract_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CensusInfoResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    chat_agent_chat_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AgentChatRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentChatResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
