"""change tract id field name in predictions table

Revision ID: 0c13696f57a8
Revises: 2f902183fc1f
Create Date: 2026-06-17 19:18:39.948170

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import geoalchemy2

1
# revision identifiers, used by Alembic.
revision: str = '0c13696f57a8'
down_revision: Union[str, Sequence[str], None] = '2f902183fc1f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('model_predictions', sa.Column('tract_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.drop_constraint(op.f('model_predictions_census_tract_id_fkey'), 'model_predictions', type_='foreignkey')
    op.create_foreign_key(None, 'model_predictions', 'census_tracts', ['tract_id'], ['tract_id'])
    op.drop_column('model_predictions', 'census_tract_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('model_predictions', sa.Column('census_tract_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'model_predictions', type_='foreignkey')
    op.create_foreign_key(op.f('model_predictions_census_tract_id_fkey'), 'model_predictions', 'census_tracts', ['census_tract_id'], ['tract_id'])
    op.drop_column('model_predictions', 'tract_id')
    # ### end Alembic commands ###
