"""update census tract model

Revision ID: 1dea35ecc6d2
Revises: ae6854e11f00
Create Date: 2026-04-07 21:12:52.151372

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '1dea35ecc6d2'
down_revision: Union[str, Sequence[str], None] = 'ae6854e11f00'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('census_demographics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tract_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('population', sa.Integer(), nullable=True),
    sa.Column('population_density', sa.Float(), nullable=True),
    sa.Column('count_age_15_64', sa.Integer(), nullable=True),
    sa.Column('household_count', sa.Integer(), nullable=True),
    sa.Column('median_household_income', sa.Float(), nullable=True),
    sa.Column('education_base_pop_25_plus', sa.Integer(), nullable=True),
    sa.Column('count_postsecondary_edu_plus', sa.Integer(), nullable=True),
    sa.Column('pct_working_age', sa.Float(), nullable=True),
    sa.Column('pct_highly_educated', sa.Float(), nullable=True),
    sa.Column('avg_household_size', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tract_id')
    )
    op.create_table('census_tracts',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tract_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('geom', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tract_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('census_tracts')
    op.drop_table('census_demographics')
    # ### end Alembic commands ###
