"""remove fk for test

Revision ID: 5222da5cbb11
Revises: 7d8945195f73
Create Date: 2026-04-07 18:29:30.226974

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '5222da5cbb11'
down_revision: Union[str, Sequence[str], None] = '7d8945195f73'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('census_demographics_tract_id_fkey'), 'census_demographics', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('census_demographics_tract_id_fkey'), 'census_demographics', 'census_tracts', ['tract_id'], ['tract_id'])
    # ### end Alembic commands ###
