"""update fk

Revision ID: 54a545016678
Revises: 1dea35ecc6d2
Create Date: 2026-04-07 21:13:42.891373

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '54a545016678'
down_revision: Union[str, Sequence[str], None] = '1dea35ecc6d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'census_demographics', 'census_tracts', ['tract_id'], ['tract_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'census_demographics', type_='foreignkey')
    # ### end Alembic commands ###
