"""upgrade type on geometry

Revision ID: 74d46d28961a
Revises: 54a545016678
Create Date: 2026-04-07 21:40:45.013980

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '74d46d28961a'
down_revision: Union[str, Sequence[str], None] = '54a545016678'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('census_tracts', 'id',
               existing_type=sa.VARCHAR(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('census_tracts', 'geom',
               existing_type=sa.VARCHAR(),
               type_=geoalchemy2.types.Geometry(geometry_type='MULTIPOLYGON', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'),
               nullable=True)
    op.create_index('idx_census_tracts_geom', 'census_tracts', ['geom'], unique=False, postgresql_using='gist')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_census_tracts_geom', table_name='census_tracts', postgresql_using='gist')
    op.alter_column('census_tracts', 'geom',
               existing_type=geoalchemy2.types.Geometry(geometry_type='MULTIPOLYGON', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'),
               type_=sa.VARCHAR(),
               nullable=False)
    op.alter_column('census_tracts', 'id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=False,
               autoincrement=True)
    # ### end Alembic commands ###
