"""create census demographics table

Revision ID: 7d8945195f73
Revises: 
Create Date: 2026-04-07 18:20:08.788450

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '7d8945195f73'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('census_tracts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tract_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('alt_geo_code', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('area_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('geometry', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_census_tracts_tract_id'), 'census_tracts', ['tract_id'], unique=True)
    op.create_table('census_demographics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tract_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('alt_geo_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('population', sa.Integer(), nullable=True),
    sa.Column('population_density', sa.Float(), nullable=True),
    sa.Column('count_age_15_64', sa.Integer(), nullable=True),
    sa.Column('household_count', sa.Integer(), nullable=True),
    sa.Column('median_household_income', sa.Float(), nullable=True),
    sa.Column('education_base_pop_25_plus', sa.Integer(), nullable=True),
    sa.Column('count_postsecondary_edu_plus', sa.Integer(), nullable=True),
    sa.Column('pct_working_age', sa.Float(), nullable=True),
    sa.Column('pct_highly_educated', sa.Float(), nullable=True),
    sa.Column('avg_household_size', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['tract_id'], ['census_tracts.tract_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tract_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('census_demographics')
    op.drop_index(op.f('ix_census_tracts_tract_id'), table_name='census_tracts')
    op.drop_table('census_tracts')
    # ### end Alembic commands ###
