"""add business table import

Revision ID: 7ebc63e03fc1
Revises: b6f8dd0e48bd
Create Date: 2026-04-11 15:37:30.951266

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import geoalchemy2

1
# revision identifiers, used by Alembic.
revision: str = '7ebc63e03fc1'
down_revision: Union[str, Sequence[str], None] = 'b6f8dd0e48bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('business',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('osm_id', sa.Integer(), nullable=False),
    sa.Column('tract_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('type', sa.Enum('FITNESS_CENTRE', 'RESTAURANT', 'CAFE', 'FAST_FOOD', 'BAR', 'SUPERMARKET', 'CONVENIENCE', 'BAKERY', 'BANK', 'CLINIC', 'DENTIST', name='businesstype'), nullable=False),
    sa.Column('category', sa.Enum('FITNESS', 'FOOD', 'RETAIL', 'SERVICE', name='businesscategory'), nullable=False),
    sa.Column('website', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('opening_hours', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.ForeignKeyConstraint(['tract_id'], ['census_tracts.tract_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('osm_id')
    )
    op.create_index(op.f('ix_business_category'), 'business', ['category'], unique=False)
    op.create_index(op.f('ix_business_tract_id'), 'business', ['tract_id'], unique=False)
    op.create_index(op.f('ix_business_type'), 'business', ['type'], unique=False)
    op.drop_index(op.f('idx_census_tracts_geom'), table_name='census_tracts', postgresql_using='gist')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_census_tracts_geom'), 'census_tracts', ['geom'], unique=False, postgresql_using='gist')
    op.drop_index(op.f('ix_business_type'), table_name='business')
    op.drop_index(op.f('ix_business_tract_id'), table_name='business')
    op.drop_index(op.f('ix_business_category'), table_name='business')
    op.drop_table('business')
    # ### end Alembic commands ###
