"""fix import

Revision ID: a6cbaf239374
Revises: 74d46d28961a
Create Date: 2026-04-07 22:15:56.354045

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import geoalchemy2

1
# revision identifiers, used by Alembic.
revision: str = 'a6cbaf239374'
down_revision: Union[str, Sequence[str], None] = '74d46d28961a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('census_tracts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tract_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='MULTIPOLYGON', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tract_id')
    )
    op.create_table('census_demographics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tract_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('population', sa.Integer(), nullable=True),
    sa.Column('population_density', sa.Float(), nullable=True),
    sa.Column('count_age_15_64', sa.Integer(), nullable=True),
    sa.Column('household_count', sa.Integer(), nullable=True),
    sa.Column('median_household_income', sa.Float(), nullable=True),
    sa.Column('education_base_pop_25_plus', sa.Integer(), nullable=True),
    sa.Column('count_postsecondary_edu_plus', sa.Integer(), nullable=True),
    sa.Column('pct_working_age', sa.Float(), nullable=True),
    sa.Column('pct_highly_educated', sa.Float(), nullable=True),
    sa.Column('avg_household_size', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['tract_id'], ['census_tracts.tract_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tract_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('census_demographics')
    op.drop_table('census_tracts')
    # ### end Alembic commands ###
