"""remove DGUID col

Revision ID: ae6854e11f00
Revises: 5222da5cbb11
Create Date: 2026-04-07 20:51:16.194173

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'ae6854e11f00'
down_revision: Union[str, Sequence[str], None] = '5222da5cbb11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('census_demographics', 'alt_geo_code')
    op.add_column('census_tracts', sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('census_tracts', sa.Column('geom', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.alter_column('census_tracts', 'id',
               existing_type=sa.INTEGER(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=False)
    op.drop_index(op.f('ix_census_tracts_tract_id'), table_name='census_tracts')
    op.create_index(op.f('ix_census_tracts_name'), 'census_tracts', ['name'], unique=False)
    op.drop_column('census_tracts', 'alt_geo_code')
    op.drop_column('census_tracts', 'geometry')
    op.drop_column('census_tracts', 'area_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('census_tracts', sa.Column('area_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('census_tracts', sa.Column('geometry', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('census_tracts', sa.Column('alt_geo_code', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_census_tracts_name'), table_name='census_tracts')
    op.create_index(op.f('ix_census_tracts_tract_id'), 'census_tracts', ['tract_id'], unique=True)
    op.alter_column('census_tracts', 'id',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_column('census_tracts', 'geom')
    op.drop_column('census_tracts', 'name')
    op.add_column('census_demographics', sa.Column('alt_geo_code', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
