"""remove optional from output table

Revision ID: b11924f0cd38
Revises: 0c13696f57a8
Create Date: 2026-07-02 23:30:39.902839

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import geoalchemy2

1
# revision identifiers, used by Alembic.
revision: str = 'b11924f0cd38'
down_revision: Union[str, Sequence[str], None] = '0c13696f57a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('model_predictions', 'total_business_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('model_predictions', 'actual_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('model_predictions', 'predicted_count',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('model_predictions', 'prediction_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('model_predictions', 'prediction_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('model_predictions', 'predicted_count',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('model_predictions', 'actual_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('model_predictions', 'total_business_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
