"""add geography tables

Revision ID: b3a38fd96105
Revises: 419eeeb588f2
Create Date: 2026-06-10 20:40:05.418356

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import geoalchemy2

1
# revision identifiers, used by Alembic.
revision: str = 'b3a38fd96105'
down_revision: Union[str, Sequence[str], None] = '419eeeb588f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('countries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('name')
    )
    op.create_table('states',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('cities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('state_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['state_id'], ['states.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cities_name'), 'cities', ['name'], unique=False)
    op.create_table('neighbourhoods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('city_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_neighbourhoods_name'), 'neighbourhoods', ['name'], unique=False)
    op.add_column('census_tracts', sa.Column('country_id', sa.Integer(), nullable=True))
    op.add_column('census_tracts', sa.Column('state_id', sa.Integer(), nullable=True))
    op.add_column('census_tracts', sa.Column('city_id', sa.Integer(), nullable=True))
    op.add_column('census_tracts', sa.Column('neighbourhood_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'census_tracts', 'states', ['state_id'], ['id'])
    op.create_foreign_key(None, 'census_tracts', 'countries', ['country_id'], ['id'])
    op.create_foreign_key(None, 'census_tracts', 'cities', ['city_id'], ['id'])
    op.create_foreign_key(None, 'census_tracts', 'neighbourhoods', ['neighbourhood_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'census_tracts', type_='foreignkey')
    op.drop_constraint(None, 'census_tracts', type_='foreignkey')
    op.drop_constraint(None, 'census_tracts', type_='foreignkey')
    op.drop_constraint(None, 'census_tracts', type_='foreignkey')
    op.drop_column('census_tracts', 'neighbourhood_id')
    op.drop_column('census_tracts', 'city_id')
    op.drop_column('census_tracts', 'state_id')
    op.drop_column('census_tracts', 'country_id')
    op.drop_index(op.f('ix_neighbourhoods_name'), table_name='neighbourhoods')
    op.drop_table('neighbourhoods')
    op.drop_index(op.f('ix_cities_name'), table_name='cities')
    op.drop_table('cities')
    op.drop_table('states')
    op.drop_table('countries')
    # ### end Alembic commands ###
