"""add business table

Revision ID: b6f8dd0e48bd
Revises: a6cbaf239374
Create Date: 2026-04-11 13:29:21.814164

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import geoalchemy2

1
# revision identifiers, used by Alembic.
revision: str = 'b6f8dd0e48bd'
down_revision: Union[str, Sequence[str], None] = 'a6cbaf239374'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
